### PR TITLE
 add code of conduct file

### PR DESCRIPTION
**Pull request by aasthakourav20**
Fixes: Issue#1

### CODE REVIEW

**Comment by aasthakourav20** [comment]
Hey @MAVRICK-1 , I made the required changes . Kindly merge the PR and add labels .

**Comment by aasthakourav20** [comment]
Hey @MAVRICK-1 , why did you rechanged the labels . My points for this PR were not added . 
Kindly answer

**Comment by aasthakourav20** [comment]
Hey @MAVRICK-1 , why did you changed the labels ?? You only said will assign it to label 3 ...

**Comment by MAVRICK-1** [comment]
@aasthakourav20 all the DOCUMENTATION and workflow are reduced to level 1. Instructions from GSSOC core team

**Comment by aasthakourav20** [comment]
> @aasthakourav20 all the DOCUMENTATION and workflow are reduced to level 2. Instructions from GSSOC core team

Okay , then please assign it to level2

**Comment by MAVRICK-1** [comment]
@aasthakourav20 sry for the mistake , i mean level1

**Pull request merged**
