### PR TITLE
there is search button at top but no input field to take user input #35

### PR DESCRIPTION
**Pull request by kapilG0**
## Related Issue
None

## Description
there is search button at top but no input field to take user input #35

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

https://github.com/MAVRICK-1/EduWeb/assets/59639410/ae9f27b6-5bb2-4388-83b5-3618485a0cb2

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by MAVRICK-1** [comment]
Thank you for submitting your pull request! 🙌 We'll review it as soon as possible. In the meantime, please ensure that your changes align with our [CONTRIBUTING.md](https://github.com/MAVRICK-1/EduWeb/blob/master/CONTRIBUTING.md.md). If there are any specific instructions or feedback regarding your PR, we'll provide them here. Thanks again for your contribution! 😊

**Comment by kapilG0** [comment]
Hello @MAVRICK-1 is there any update related to this pr ?

**Comment by kapilG0** [comment]
> Hello @MAVRICK-1 is there any update related to this pr ?

i have resolved conflicts please check now thanks

**Comment by kapilG0** [comment]
Hello @MAVRICK-1 as you have merged can you close or can I close that ?

**Comment by MAVRICK-1** [comment]
@kapilG0 you can close

**Pull request merged**
