### PR TITLE
Added contact form

### PR DESCRIPTION
**Pull request by masterboy376**
## Related Issue
[[Feature Request]: Adding a contact/enquiry form #34](https://github.com/MAVRICK-1/EduWeb/issues/34)

## Description
This PR adds a contact form which allow users to send their inquiries via email, using EmailJS.
To test it create account on email.js and create your service and template the replace `YOUR_SERVICE_ID`, `YOUR_TEMPLATE_ID`, `YOUR_PUBLIC_KEY` in scripts.js with your credentials. Now after this step when ever anyone fills contact form then the inquiry will be sent to the admins email.

## Type of PR

- [ ] Bug fix
- [x] Feature addition
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
Screenshot (163)
Screenshot (164)

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by MAVRICK-1** [comment]
Thank you for submitting your pull request! 🙌 We'll review it as soon as possible. In the meantime, please ensure that your changes align with our [CONTRIBUTING.md](https://github.com/MAVRICK-1/EduWeb/blob/master/CONTRIBUTING.md.md). If there are any specific instructions or feedback regarding your PR, we'll provide them here. Thanks again for your contribution! 😊

**Comment by masterboy376** [comment]
Hello @MAVRICK-1, PTAL

**Comment by MAVRICK-1** [comment]
@masterboy376 great  work link it with navbar contact tab.

**Comment by masterboy376** [comment]
> @masterboy376 great  work link it with navbar contact tab.

Hello @MAVRICK-1, I think I did it. 
`            <a href="#contact" class="navbar-link" data-nav-link>Contact</a>`

**Comment by MAVRICK-1** [comment]
@masterboy376 great work

**Pull request merged**
