### PR TITLE
Added User Testimonials section

### PR DESCRIPTION
**Pull request by Devaki01**
## Related Issue
This is with reference to #76 . 

## Description
As assigned, I have added an interactive user testimonials section to the website. 

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
image

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
Please review the PR and kindly let me know if any additional changes are required.

### CODE REVIEW

**Comment by MAVRICK-1** [comment]
https://github.com/MAVRICK-1/EduWeb/assets/146999057/53842f42-e55f-499e-8ca9-1a39faf6d8d9

@Devaki01 make it responsive and a bit of jerking occurring  on other testimonials while hovering on it , fix that

**Comment by Devaki01** [comment]
ok, will make it responsive and fix the jerking as well.

**Comment by Devaki01** [comment]
> Recording.2024-07-01.162027.mp4 
> @Devaki01 make it responsive and a bit of jerking occurring on other testimonials while hovering on it , fix that

Hello,
I have made it responsive and fixed the jerking issue as well. Please review it once.

**Comment by MAVRICK-1** [comment]
@Devaki01 thanx will look into it by today

**Comment by MAVRICK-1** [comment]
@Devaki01 there are few minor issues like width of faq and Nav Icon responsive design, but overall looks fine.

**Pull request merged**
