### PR TITLE
login page created

### LINKED ISSUE #41: [Feature Request]: Login Page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

When clicking on Try for Free button nothing happens so I want to make a login page for the same.Kindly assign me this issue @M

### Use Case

Enchancing Interface.

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Ojas-Arora**
## Related Issue
Fixes #41 

## Description
Login/Signup Page created 

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
NA

### CODE REVIEW

**Comment by MAVRICK-1** [comment]
Thank you for submitting your pull request! 🙌 We'll review it as soon as possible. In the meantime, please ensure that your changes align with our [CONTRIBUTING.md](https://github.com/MAVRICK-1/EduWeb/blob/master/CONTRIBUTING.md.md). If there are any specific instructions or feedback regarding your PR, we'll provide them here. Thanks again for your contribution! 😊

**Comment by MAVRICK-1** [comment]
Screenshot 2024-05-31 191706



@Ojas-Arora great word just make it responsive then it is ready to merge

**Comment by Ojas-Arora** [comment]
@MAVRICK-1 I have made page responsive and added some additional features to it. Please review

**Comment by MAVRICK-1** [comment]
https://github.com/MAVRICK-1/EduWeb/assets/146999057/a4b81939-b464-4481-977d-40b9e83f8dd0


@Ojas-Arora

**Comment by Ojas-Arora** [comment]
What do you want to convey @MAVRICK-1 ?

**Comment by MAVRICK-1** [comment]
> What do you want to convey @MAVRICK-1 ?

Shouldn't that spinning card be hidden ?

**Comment by Ojas-Arora** [comment]
You want the spinning card to be hidden @MAVRICK-1 ?

**Comment by MAVRICK-1** [comment]
https://youtu.be/rWQeqH526KA?si=UOgzMQNaHl7zbi12   @Ojas-Arora shoudn't it be something like ?

**Comment by Ojas-Arora** [comment]
Ok I will make like this @MAVRICK-1

**Comment by Ojas-Arora** [comment]
@MAVRICK-1 Please review the changes

**Pull request merged**
