### PR TITLE
Added icons to NavLinks in the Navbar

### PR DESCRIPTION
**Pull request by Devaki01**
## Related Issue
This is with reference to issue #77. 

## Description
As assigned, I have added icons to the NavLinks in the navbar.

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
image

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
Please review the PR and kindly let me know if any additional changes are required.

### CODE REVIEW

**Comment by MAVRICK-1** [comment]
Thank you for submitting your pull request! 🙌 We'll review it as soon as possible. In the meantime, please ensure that your changes align with our [CONTRIBUTING.md](https://github.com/MAVRICK-1/EduWeb/blob/master/CONTRIBUTING.md.md). If there are any specific instructions or feedback regarding your PR, we'll provide them here. Thanks again for your contribution! 😊

**Comment by MAVRICK-1** [comment]
@Devaki01 can you make the faq and navbar responsive ? i will add level 3 to it then

**Comment by Devaki01** [comment]
> @Devaki01 can you make the faq and navbar responsive ? i will add level 3 to it then

ok, will do it

**Comment by Devaki01** [comment]
> @Devaki01 can you make the faq and navbar responsive ? i will add level 3 to it then

Hello,
I have made the FAQ section responsive. 
image
image
image

But will you please specify exactly what all changes are required in the navbar because it is already responsive. I make the further required changes.

**Comment by MAVRICK-1** [comment]
@Devaki01 great work 👏, but due to the guidelines, I can't mark it level 3

**Pull request merged**
