### PR TITLE
Added link to contact button on navbar

### PR DESCRIPTION
**Pull request by SaranshBangar**
## Related Issue
Issue #56 

## Description
[Please include a brief description of the changes or features added]

## Type of PR

- [X] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
Respected maintainers, please provide relevant tags to both the PR and the Issue

### CODE REVIEW

**Comment by MAVRICK-1** [comment]
Thank you for submitting your pull request! 🙌 We'll review it as soon as possible. In the meantime, please ensure that your changes align with our [CONTRIBUTING.md](https://github.com/MAVRICK-1/EduWeb/blob/master/CONTRIBUTING.md.md). If there are any specific instructions or feedback regarding your PR, we'll provide them here. Thanks again for your contribution! 😊

**Comment by SaranshBangar** [comment]
Resolves issue #56

**Comment by SaranshBangar** [comment]
@MAVRICK-1 sir please add relevant level label to both the issue and the PR

**Comment by MAVRICK-1** [comment]
> @MAVRICK-1 sir please add relevant level label to both the issue and the PR

you will get 1 point for this . gssoc = 1 point

**Pull request merged**
